#!/bin/bash
read -p "Enter first floating point number: " num1
read -p "Enter second floating point number: " num2
read -p "Select operation (+, -, *, /): " operator

case $operator in
    +) result=$(echo "$num1 + $num2" | bc);;
    -) result=$(echo "$num1 - $num2" | bc);;
    \*) result=$(echo "$num1 * $num2" | bc);;
    /) result=$(echo "$num1 / $num2" | bc);;
esac

echo "$num1 $operator $num2 = $result"

