#!/bin/bash
read -p "Enter first integer: " num1
read -p "Enter second integer: " num2
read -p "Select operation (+, -, *, /): " operator

case $operator in
    +) result=$((num1 + num2));;
    -) result=$((num1 - num2));;
    \*) result=$((num1 * num2));;
    /) result=$((num1 / num2));;
esac

echo "$num1 $operator $num2 = $result"

