#!/bin/bash

op1=$1 
operator=$2 
op2=$3 

case $operator in 
   +) result=$(expr $op1 + $op2);; 
   -) result=$(expr $op1 - $op2);; 
   \*) result=$(expr $op1 \* $op2);; 
   /) result=$(expr $op1 / $op2);; 
   %) result=$(expr $op1 % op2);; 
   **) result=$(expr $op1 \*\* op2);; 
esac 

echo "$op1 $operator $op2 = $result"

